import { jsPDF } from 'jspdf';
import { PlayerResult, GamePhoto } from '../types';

const SEND_EMAIL_URL = '/.netlify/functions/send-email';
const SITE_URL = 'https://games.eventday.dk';

interface SendEmailPayload {
  to: string;
  subject: string;
  html: string;
  attachments?: { filename: string; content?: string; path?: string }[];
}

async function callSendEmail(payload: SendEmailPayload) {
  const res = await fetch(SEND_EMAIL_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || 'Failed to send email');
  return data;
}

export function generateResultsPDF(gameName: string, results: PlayerResult[]): string {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('TEAMCHALLENGE', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(gameName, pageWidth / 2, 30, { align: 'center' });

  // Line separator
  doc.setDrawColor(234, 88, 12);
  doc.setLineWidth(1);
  doc.line(20, 35, pageWidth - 20, 35);

  // Table header
  const startY = 45;
  const colRank = 25;
  const colName = 45;
  const colScore = pageWidth - 25;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text('RANK', colRank, startY);
  doc.text('TEAM', colName, startY);
  doc.text('SCORE', colScore, startY, { align: 'right' });

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, startY + 2, pageWidth - 20, startY + 2);

  // Table rows
  let y = startY + 10;
  const rowHeight = 8;

  results.forEach((player) => {
    if (y > 275) {
      doc.addPage();
      y = 20;
    }

    const isTop3 = player.position <= 3;

    if (isTop3) {
      doc.setFillColor(255, 247, 237);
      doc.rect(20, y - 5, pageWidth - 40, rowHeight, 'F');
    }

    doc.setFont('helvetica', isTop3 ? 'bold' : 'normal');
    doc.setFontSize(isTop3 ? 12 : 10);
    doc.setTextColor(isTop3 ? 234 : 60, isTop3 ? 88 : 60, isTop3 ? 12 : 60);

    const rankLabel = player.position <= 3
      ? ['', '1st', '2nd', '3rd'][player.position]
      : `#${player.position}`;

    doc.text(rankLabel, colRank, y);
    doc.text(player.name, colName, y);
    doc.text(player.score.toLocaleString(), colScore, y, { align: 'right' });

    y += rowHeight;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by TeamChallenge • ${new Date().toLocaleDateString()}`, pageWidth / 2, 290, { align: 'center' });

  // Return base64 without the data URI prefix
  const base64 = doc.output('datauristring');
  return base64.split(',')[1];
}

function buildResultsHtml(gameName: string, gameId: string, results: PlayerResult[]): string {
  const top3 = results.slice(0, 3);
  const rest = results.slice(3);

  const medalEmojis = ['🥇', '🥈', '🥉'];

  const topRows = top3.map((p, i) =>
    `<tr style="background:#FFF7ED;">
      <td style="padding:12px 16px;font-weight:bold;font-size:18px;">${medalEmojis[i]}</td>
      <td style="padding:12px 16px;font-weight:bold;font-size:16px;">${p.name}</td>
      <td style="padding:12px 16px;text-align:right;font-weight:bold;font-size:16px;">${p.score.toLocaleString()}</td>
    </tr>`
  ).join('');

  const restRows = rest.map(p =>
    `<tr>
      <td style="padding:8px 16px;color:#666;">#${p.position}</td>
      <td style="padding:8px 16px;">${p.name}</td>
      <td style="padding:8px 16px;text-align:right;font-family:monospace;">${p.score.toLocaleString()}</td>
    </tr>`
  ).join('');

  return `
    <div style="font-family:'Helvetica Neue',Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #eee;">
      <div style="background:#1C1917;padding:32px;text-align:center;">
        <h1 style="color:#F59E0B;margin:0;font-size:28px;letter-spacing:2px;">TEAMCHALLENGE</h1>
        <p style="color:#A1A1AA;margin:8px 0 0;font-size:14px;">${gameName}</p>
      </div>
      <div style="padding:24px;">
        <table style="width:100%;border-collapse:collapse;">
          <thead>
            <tr style="border-bottom:2px solid #EA580C;">
              <th style="padding:8px 16px;text-align:left;color:#999;font-size:11px;">RANK</th>
              <th style="padding:8px 16px;text-align:left;color:#999;font-size:11px;">TEAM</th>
              <th style="padding:8px 16px;text-align:right;color:#999;font-size:11px;">SCORE</th>
            </tr>
          </thead>
          <tbody>
            ${topRows}
            ${restRows}
          </tbody>
        </table>
      </div>
      <div style="padding:16px 24px 24px;text-align:center;">
        <a href="${SITE_URL}/?game=${gameId}&view=results" style="display:inline-block;padding:12px 32px;background:#EA580C;color:#fff;text-decoration:none;border-radius:8px;font-weight:bold;font-size:14px;letter-spacing:1px;">VIEW LIVE RESULTS</a>
      </div>
      <div style="padding:16px;text-align:center;color:#aaa;font-size:11px;border-top:1px solid #eee;">
        Powered by TeamChallenge • eventday.dk
      </div>
    </div>
  `;
}

function buildShowtimeHtml(gameName: string, gameId: string, photos: GamePhoto[]): string {
  const thumbnails = photos.slice(0, 12).map(p =>
    `<div style="width:30%;margin:1.5%;border-radius:8px;overflow:hidden;">
      <img src="${p.thumbnailUrl || p.url}" alt="${p.teamName || ''}" style="width:100%;height:auto;display:block;" />
    </div>`
  ).join('');

  return `
    <div style="font-family:'Helvetica Neue',Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #eee;">
      <div style="background:#1C1917;padding:32px;text-align:center;">
        <h1 style="color:#EC4899;margin:0;font-size:28px;letter-spacing:2px;">SHOWTIME</h1>
        <p style="color:#A1A1AA;margin:8px 0 0;font-size:14px;">${gameName} • ${photos.length} photos</p>
      </div>
      <div style="padding:24px;display:flex;flex-wrap:wrap;">
        ${thumbnails}
      </div>
      <div style="padding:16px 24px 24px;text-align:center;">
        <a href="${SITE_URL}/?game=${gameId}&view=showtime" style="display:inline-block;padding:12px 32px;background:#EC4899;color:#fff;text-decoration:none;border-radius:8px;font-weight:bold;font-size:14px;letter-spacing:1px;">VIEW ALL PHOTOS</a>
      </div>
      <div style="padding:16px;text-align:center;color:#aaa;font-size:11px;border-top:1px solid #eee;">
        Powered by TeamChallenge • eventday.dk
      </div>
    </div>
  `;
}

export async function sendResultsEmail(
  to: string,
  gameName: string,
  gameId: string,
  results: PlayerResult[]
) {
  const html = buildResultsHtml(gameName, gameId, results);
  const pdfBase64 = generateResultsPDF(gameName, results);

  const safeName = gameName.replace(/[^a-zA-Z0-9-_ ]/g, '').trim() || 'results';

  return callSendEmail({
    to,
    subject: `TeamChallenge Results: ${gameName}`,
    html,
    attachments: [
      {
        filename: `${safeName}-results.pdf`,
        content: pdfBase64,
      },
    ],
  });
}

export async function sendShowtimeEmail(
  to: string,
  gameName: string,
  gameId: string,
  allPhotos: GamePhoto[],
  selectedPhotos: GamePhoto[]
) {
  const html = buildShowtimeHtml(gameName, gameId, allPhotos);

  const attachments = selectedPhotos.map((photo, i) => ({
    filename: `${photo.teamName || 'photo'}-${i + 1}.jpg`,
    path: photo.url,
  }));

  return callSendEmail({
    to,
    subject: `TeamChallenge Photos: ${gameName}`,
    html,
    attachments: attachments.length > 0 ? attachments : undefined,
  });
}
